apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: complette-sonarqube-github-action
  title: Complete Sonarqube GitHub Action
  description: Creates Sonarqube Scan via GitHub Action
spec:
  owner: sbroersma
  type: service

  parameters:
    - title: Sonarqube GitHub Action inputs
      required:
        - repoUrl
        - sonarqubeKey
      properties:
        sonarqubeKey:
          title: Sonarqube project key
          type: string
          description: Unique Sonarqube project key
        repoUrl:
            title: Target Repository Location
            type: string
            ui:field: RepoUrlPicker
            ui:options:
              allowedHosts:
                - github.com
      
  steps:
    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        targetPath: ./
        url: https://github.com/sbroersma/sonarqube_gha/tree/main/sonarqube_workflow
        
    - id: publish_sonar_gha
      name: Publish Sonarqube GitHub Action
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Sonarqube_Scan_Workflow" #"${{parameters.branchName}}"
        branchName: "Sonarqube_Scan_Workflow" #create-${{parameters.branchName}}
        description: |
          # New project: ${{parameters.branchName}}
          "Create files to create GitHub Action for Sonarqube Scan" #${{ parameters.description if parameters.description }}
        targetPath: ./.github/workflows/ #${{ parameters.targetPath if parameters.targetPath else parameters.branchName }}

    - id: create_file
      name: Create Sonarqube project properties file
      action: catalog:write
      input:
        filePath: ./sonar-project.properties
        entity:
          sonar.projectKey: ${{ parameters.sonarqubeKey }}
    
    - id: publish_sonar_properties
      name: Publish Sonar Project Properties
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Sonarqube project property file"
        branchName: "Sonarqube_project_properties"
        description: "Create sonar project properties file"
        sourcePath: ./
        targetPath: ./



  output:
    links:
      - url: ${{steps.publish_sonar_gha.output.remoteUrl}}
        text: "Go to Sonarqube GitHub Action PR"
      - url: ${{steps.publish_sonar_properties.output.remoteUrl}}
        text: "Go to Sonar Properties Pull Request"