apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: complette-sonarqube-github-action
  title: Complete Sonarqube GitHub Action
  description: Creates Sonarqube Scan via GitHub Action
spec:
  owner: sbroersma
  type: service

  parameters:
    - title: Sonarqube GitHub Action inputs
      required:
        - repoUrl
      properties:
        repoUrl:
            title: Target Repository Location
            type: string
            ui:field: RepoUrlPicker
            ui:options:
              allowedHosts:
                - github.com
      
  steps:
    - id: fetch-docs
      name: Fetch Docs
      action: fetch:plain
      input:
        targetPath: ./
        url: https://github.com/sbroersma/sonarqube_gha/tree/main/sonarqube_workflow
        
    - id: publish
      name: Publish
      action: publish:github:pull-request
      input:
        repoUrl: ${{ parameters.repoUrl }}
        title: "Sonarqube_Scan_Workflow" #"${{parameters.branchName}}"
        branchName: "Sonarqube_Scan_Workflow" #create-${{parameters.branchName}}
        description: |
          # New project: ${{parameters.branchName}}
          "Create files to create GitHub Action for Sonarqube Scan" #${{ parameters.description if parameters.description }}
        targetPath: ./.github/workflows/ #${{ parameters.targetPath if parameters.targetPath else parameters.branchName }}

  output:
    links:
      - url: ${{steps.publish.output.remoteUrl}}
        text: "Go to PR"